export const firstRowBtns = [
  { itemEng: '`', itemRu: 'ё', valueEng: '`', valueRu: 'ё', code: 192 },
  { itemEng: '1', itemRu: '1', valueEng: 1, valueRu: 1, code: 49 },
  { itemEng: '2', itemRu: '2', valueEng: 2, valueRu: 2, code: 50 },
  { itemEng: '3', itemRu: '3', valueEng: 3, valueRu: 3, code: 51 },
  { itemEng: '4', itemRu: '4', valueEng: 4, valueRu: 4, code: 52 },
  { itemEng: '5', itemRu: '5', valueEng: 5, valueRu: 5, code: 53 },
  { itemEng: '6', itemRu: '6', valueEng: 6, valueRu: 6, code: 54 },
  { itemEng: '7', itemRu: '7', valueEng: 7, valueRu: 7, code: 55 },
  { itemEng: '8', itemRu: '8', valueEng: 8, valueRu: 8, code: 56 },
  { itemEng: '9', itemRu: '9', valueEng: 9, valueRu: 9, code: 57 },
  { itemEng: '0', itemRu: '0', valueEng: 0, valueRu: 0, code: 48 },
  { itemEng: '-', itemRu: '-', valueEng: '-', valueRu: '-', code: 189 },
  { itemEng: '=', itemRu: '=', valueEng: '=', valueRu: '=', code: 187 },
  { itemEng: 'backspace', itemRu: 'backspace', valueEng: '', valueRu: '', code: 8 },
];

export const secondRowBtns = [
  { itemEng: 'Tab', valueEng: ' ', itemRu: 'Tab', valueRu: '  ', code: 9 },
  { itemEng: 'q', itemRu: 'й', valueEng: 'q', valueRu: 'й', code: 81 },
  { itemEng: 'w', itemRu: 'ц', valueEng: 'w', valueRu: 'ц', code: 87 },
  { itemEng: 'e', itemRu: 'у', valueEng: 'e', valueRu: 'у', code: 69 },
  { itemEng: 'r', itemRu: 'к', valueEng: 'r', valueRu: 'к', code: 82 },
  { itemEng: 't', itemRu: 'е', valueEng: 't', valueRu: 'е', code: 84 },
  { itemEng: 'y', itemRu: 'н', valueEng: 'y', valueRu: 'н', code: 89 },
  { itemEng: 'u', itemRu: 'г', valueEng: 'u', valueRu: 'г', code: 85 },
  { itemEng: 'i', itemRu: 'ш', valueEng: 'i', valueRu: 'ш', code: 73 },
  { itemEng: 'o', itemRu: 'щ', valueEng: 'o', valueRu: 'щ', code: 79 },
  { itemEng: 'p', itemRu: 'з', valueEng: 'p', valueRu: 'з', code: 80 },
  { itemEng: '[', itemRu: 'х', valueEng: '[', valueRu: 'х', code: 219 },
  { itemEng: ']', itemRu: 'ъ', valueEng: ']', valueRu: 'ъ', code: 221 },
  { itemEng: '\/', itemRu: '\/', valueEng: '\/', code: 220 },
];

export const thirdRowBtns = [
  { itemEng: 'CapsLock', valueEng: '', itemRu: 'CapsLock', valueRu: '', code: 20 },
  { itemEng: 'a', itemRu: 'ф', valueEng: 'a', valueRu: 'ф', code: 65 },
  { itemEng: 's', itemRu: 'ы', valueEng: 's', valueRu: 'ы', code: 83 },
  { itemEng: 'd', itemRu: 'в', valueEng: 'd', valueRu: 'в', code: 68 },
  { itemEng: 'f', itemRu: 'а', valueEng: 'f', valueRu: 'а', code: 70 },
  { itemEng: 'g', itemRu: 'п', valueEng: 'g', valueRu: 'п', code: 71 },
  { itemEng: 'h', itemRu: 'р', valueEng: 'h', valueRu: 'р', code: 72 },
  { itemEng: 'j', itemRu: 'о', valueEng: 'j', valueRu: 'о', code: 74 },
  { itemEng: 'k', itemRu: 'л', valueEng: 'k', valueRu: 'л', code: 75 },
  { itemEng: 'l', itemRu: 'д', valueEng: 'l', valueRu: 'д', code: 76 },
  { itemEng: ';', itemRu: 'ж', valueEng: ';', valueRu: 'ж', code: 186 },
  { itemEng: '"', itemRu: 'э', valueEng: '"', valueRu: 'э', code: 222 },
  { itemEng: 'Enter', itemRu: 'Enter', valueEng: '', valueRu: '', code: 13 },
];