export const firstRowBtns = [
  { itemEng: '`', itemRu: 'ё', valueEng: '`', valueRu: 'ё', code: 'Backquote' },
  { itemEng: '1', itemRu: '1', valueEng: 1, valueRu: 1, code: 'Digit1' },
  { itemEng: '2', itemRu: '2', valueEng: 2, valueRu: 2, code: 'Digit2' },
  { itemEng: '3', itemRu: '3', valueEng: 3, valueRu: 3, code: 'Digit3' },
  { itemEng: '4', itemRu: '4', valueEng: 4, valueRu: 4, code: 'Digit4' },
  { itemEng: '5', itemRu: '5', valueEng: 5, valueRu: 5, code: 'Digit5' },
  { itemEng: '6', itemRu: '6', valueEng: 6, valueRu: 6, code: 'Digit6' },
  { itemEng: '7', itemRu: '7', valueEng: 7, valueRu: 7, code: 'Digit7' },
  { itemEng: '8', itemRu: '8', valueEng: 8, valueRu: 8, code: 'Digit8' },
  { itemEng: '9', itemRu: '9', valueEng: 9, valueRu: 9, code: 'Digit9' },
  { itemEng: '0', itemRu: '0', valueEng: 0, valueRu: 0, code: 'Digit0' },
  { itemEng: '-', itemRu: '-', valueEng: '-', valueRu: '-', code: 'Minus' },
  { itemEng: '=', itemRu: '=', valueEng: '=', valueRu: '=', code: 'Equal' },
  { itemEng: 'Backspace', itemRu: 'Backspace', valueEng: '', valueRu: '', code: 'Backspace' },
];

export const secondRowBtns = [
  { itemEng: 'Tab', valueEng: ' ', itemRu: 'Tab', valueRu: '  ', code: 'Tab' },
  { itemEng: 'q', itemRu: 'й', valueEng: 'q', valueRu: 'й', code: 'KeyQ' },
  { itemEng: 'w', itemRu: 'ц', valueEng: 'w', valueRu: 'ц', code: 'KeyW' },
  { itemEng: 'e', itemRu: 'у', valueEng: 'e', valueRu: 'у', code: 'KeyE' },
  { itemEng: 'r', itemRu: 'к', valueEng: 'r', valueRu: 'к', code: 'KeyR' },
  { itemEng: 't', itemRu: 'е', valueEng: 't', valueRu: 'е', code: 'KeyT' },
  { itemEng: 'y', itemRu: 'н', valueEng: 'y', valueRu: 'н', code: 'KeyY' },
  { itemEng: 'u', itemRu: 'г', valueEng: 'u', valueRu: 'г', code: 'KeyU' },
  { itemEng: 'i', itemRu: 'ш', valueEng: 'i', valueRu: 'ш', code: 'KeyI' },
  { itemEng: 'o', itemRu: 'щ', valueEng: 'o', valueRu: 'щ', code: 'KeyO' },
  { itemEng: 'p', itemRu: 'з', valueEng: 'p', valueRu: 'з', code: 'KeyP' },
  { itemEng: '[', itemRu: 'х', valueEng: '[', valueRu: 'х', code: 'BracketLeft' },
  { itemEng: ']', itemRu: 'ъ', valueEng: ']', valueRu: 'ъ', code: 'BracketRight' },
  { itemEng: '\/', itemRu: '\/', valueEng: '\/', code: 'Backslash' },
];

export const thirdRowBtns = [
  { itemEng: 'CapsLock', valueEng: '', itemRu: 'CapsLock', valueRu: '', code: 'CapsLock' },
  { itemEng: 'a', itemRu: 'ф', valueEng: 'a', valueRu: 'ф', code: 'KeyA' },
  { itemEng: 's', itemRu: 'ы', valueEng: 's', valueRu: 'ы', code: 'KeyS' },
  { itemEng: 'd', itemRu: 'в', valueEng: 'd', valueRu: 'в', code: 'KeyD' },
  { itemEng: 'f', itemRu: 'а', valueEng: 'f', valueRu: 'а', code: 'KeyF' },
  { itemEng: 'g', itemRu: 'п', valueEng: 'g', valueRu: 'п', code: 'KeyG' },
  { itemEng: 'h', itemRu: 'р', valueEng: 'h', valueRu: 'р', code: 'KeyH' },
  { itemEng: 'j', itemRu: 'о', valueEng: 'j', valueRu: 'о', code: 'KeyJ' },
  { itemEng: 'k', itemRu: 'л', valueEng: 'k', valueRu: 'л', code: 'KeyK' },
  { itemEng: 'l', itemRu: 'д', valueEng: 'l', valueRu: 'д', code: 'KeyL' },
  { itemEng: ';', itemRu: 'ж', valueEng: ';', valueRu: 'ж', code: 'Semicolon' },
  { itemEng: '"', itemRu: 'э', valueEng: '"', valueRu: 'э', code: 'Quote' },
  { itemEng: 'Enter', itemRu: 'Enter', valueEng: '', valueRu: '', code: 'Enter' },
];

export const fourthRowBtns = [
  { itemEng: 'Shift', itemRu: 'Shift', valueEng: '', valueRu: '', code: 'ShiftLeft' },
  { itemEng: 'z', itemRu: 'я', valueEng: 'z', valueRu: 'я', code: 'KeyZ' },
  { itemEng: 'x', itemRu: 'ч', valueEng: 'x', valueRu: 'ч', code: 'KeyX' },
  { itemEng: 'c', itemRu: 'с', valueEng: 'c', valueRu: 'с', code: 'KeyC' },
  { itemEng: 'v', itemRu: 'м', valueEng: 'v', valueRu: 'м', code: 'KeyV' },
  { itemEng: 'b', itemRu: 'и', valueEng: 'b', valueRu: 'и', code: 'KeyB' },
  { itemEng: 'n', itemRu: 'т', valueEng: 'n', valueRu: 'т', code: 'KeyN' },
  { itemEng: 'm', itemRu: 'ь', valueEng: 'm', valueRu: 'ь', code: 'KeyM' },
  { itemEng: ',', itemRu: 'б', valueEng: ',', valueRu: 'б', code: 'Comma' },
  { itemEng: '.', itemRu: 'ю', valueEng: '.', valueRu: 'ю', code: 'Period' },
  { itemEng: '/', itemRu: '.', valueEng: '/', valueRu: '.', code: 'Slash' },
  { itemEng: '↑', itemRu: '↑', valueEng: '↑', valueRu: '↑', code: 'ArrowUp' },
  { itemEng: 'Shift', itemRu: 'Shift', valueEng: '', valueRu: '', code: 'ShiftRight' },
];

export const fifthRowBtns = [
  { itemEng: 'Ctrl', itemRu: 'Ctrl', valueEng: '', valueRu: '', code: 'ControlLeft' },
  { itemEng: 'Win', itemRu: 'Win', valueEng: '', valueRu: '', code: 'MetaLeft' },
  { itemEng: 'Alt', itemRu: 'Alt', valueEng: '', valueRu: '', code: 'AltLeft' },
  { itemEng: '', itemRu: '', valueEng: ' ', valueRu: ' ', code: 'Space' },
  { itemEng: 'Alt', itemRu: 'Alt', valueEng: '', valueRu: '', code: 'AltRight' },
  { itemEng: 'Ctrl', itemRu: 'Ctrl', valueEng: '', valueRu: '', code: 'ControlRight' },
  { itemEng: '←', itemRu: '←', valueEng: '←', valueRu: '←', code: 'ArrowLeft' },
  { itemEng: '↓', itemRu: '↓', valueEng: '↓', valueRu: '↓', code: 'ArrowDown' },
  { itemEng: '→', itemRu: '→', valueEng: '→', valueRu: '→', code: 'ArrowRight' },
];